import math
#variablen des Programms
AF = 0
AJAHR = 0
ALTER1 = 0
ENTSCH = 0
F = 0
JFREIB = 0 #
JHINZU = 0 #
JRE4 = 0
JRE4ENT = 1
JVBEZ = 0 #
KRV = 0
KVZ = 1.60
LZZ = 0
LZZFREIB = 0 
LZZHINZU = 0
MBV = 0
PKPV = 0
PKV = 0
PVS = 0
PVZ = 0
R = 0 #keine Religion
RE4 = 0
SONSTB = 0 #
SONSTENT = 0
STERBE = 0
STKL = 0
VBEZ = 0 #
VBEZM = 0
VBEZS = 0
VBS = 0 #
VJAHR = 0
VKAPA = 0 #
VMT = 0 #
ZKF = 0
ZMVB = 0 #1 wenn LZZ=1 ist

#Ausgangsparameter
BK = 1
BKS = 1
BKV = 1
LSTLZZ = 1
SOLZLZZ = 1
SOLZS = 1
SOLZV = 1
STS = 1
STV = 1
VKVLZZ = 1
VKVSONST = 1

#Ausgangsparameter DBA
VFRB = 0 
VFRBS1 = 0
VFRBS2 = 0
WVFRB = 0
WVFRBM = 0
WVFRBO = 0

# Interne Felder
ALTE = 1
ANP = 1
ANTEIL1 = 1
BBGKVPV = 1
BBGRV = 1
BMG = 1
DIFF = 1
EFA = 1
FVB = 1
FVBSO = 1
FVBZ = 1
FVBZSO = 1
GFB = 1
HBALTE = 1
HFVB = 1
HFVBZ = 1
HFVBZSO = 1
HOCH = 1
J = 1
JBMG = 1
JLFREIB = 1
JLHINZU = 1
JW = 1
K = 1
KENNVMT = 1
KFB = 1
KVSATZAG = 1
KVSATZAN = 1
KZTAB = 1
LSTJAHR = 1
LST1 = 1
LST2 = 1
LST3 = 1
LSTOSO = 1
LSTSO = 1
MIST = 1
PVSATZAG = 1
PVSATZAN = 1
RVSATZAN = 1
RW = 1
SAP = 1
SOLZFREI = 1
SOLZJ = 1
SOLZMIN = 1
SOLZSBMG = 1
SOLZSZVE = 1
SOLZVBMG = 1
ST = 1
ST1 = 1
St2 = 1
STOVMT = 1
TAB1 = 1
TAB2 = 1
TAB3 = 1
TAB4 = 1
TAB5 = 1
TBSVORV = 1
VBEZB = 1
VBEZBSO = 1
VERGL = 1
VHB = 1
VKV = 1
VSP = 1
VSPN = 1
VSP1 = 1
VSP2 = 1
VSP3 = 1
W1STKL5 = 1
W2STKL5 = 1
W3STKL5 = 1
X = 1
Y = 1
ZRE4 = 1
ZRE4J = 1
ZRE4VP = 1
ZTABFB = 1
ZVBEZ = 1
ZVBEZJ = 1
ZVE = 1
ZX = 1
ZZX = 1
        
#interne variabeln
def eingeben():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    print("Lohnsteuer 2023 (c) cj \n")
    LZZ = int(input("Zeitraum des Lohnes: 1 = Jahr, 2 = Monat, 3 = Woche, 4 = Tag"))
    RE4 = int(input("Bruttogehalt (in Cent) in diesem Zeitraum: ")) * 100
    STKL = int(input("Ihre Steuerklasse: 1....6 :"))
    ZKF = float(input("Ihr Kinderfreibetrag: 0 ,0.5, 1, 1.5,......10.0 :"))
    R = int(input("Kirchensteuer: 1 = Ja, 0 = Nein :"))

def MPARA():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    if KRV < 2:
        if KRV == 0:
            BBGRV = 87600
        else:
            BBGRV = 85200
        RVSATZAN = 0.093
        TBSVORV = 1.00
    BBGKVPV = 59850
    KVSATZAN = KVZ/2/100 + 0.07
    KVSATZAG = 0.008 + 0.07
    if PVS == 1:
        PVSATZAN = 0.02025
        PVSATZAG = 0.01025
    else:
        PVSATZAN = 0.01525
        PVSATZAG = 0.01525
    if PVZ == 1:
        PVSATZAN = PVSATZAN + 0.0035
    PVSATZAN = PVSATZAN + 0.0035
    W2STKL5 = 31404
    W3STKL5 = 222260
    GFB = 10908
    SOLZFREI = 17543
   
def MRE4JL():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    if LZZ == 1:
        ZRE4J = RE4/100
        ZVBEZJ = VBEZ/100
        JLFREIB = LZZFREIB/100
        JLHINZU = LZZHINZU/100
    elif LZZ == 2:
            ZRE4J = RE4*12/100
            ZVBEZJ = VBEZ*12/100
            JLFREIB = LZZFREIB*12/100
            JLHINZU = LZZHINZU*12/100
    elif LZZ == 3:
            ZRE4J = RE4*360/7/100
            ZVBEZJ = VBEZ*360/7/100
            JLFREIB = LZZFREIB*360/7/100
            JLHINZU = LZZHINZU*360/7/100
    elif LZZ == 4:
            ZRE4J = RE4*360/100
            ZVBEZJ = VBEZ*360/100
            JLFREIB = LZZFREIB*360/100
            JLHINZU = LZZHINZU*360/100
    if AF == 0:
        F = 1

def MRE4():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    if ZVBEZJ == 0:
        FVBZ = 0
        FVB = 0
        FVBZSO = 0
        FVBSO = 0
    elif VJAHR < 2006:
        J = 1
    elif VJAHR < 2040:
        J = VJAHR - 2004
    else:
        J = 36
    if LZZ == 1:
        VBEZB = VBEZM * ZMVB + VBEZS
        HFVB = TAB2(J) / 12 * ZMVB
        FVBZ = math.ceil(TAB3(J) / 12 * ZMVB)
    else:
        VBEZB = VBEZM * 12 + VBEZS
        HFVB = TAB2(J)
        FVBZ = TAB3(J)
    FVB = math.ceil(VBEZB * TAB1(J) / 100)
    if FVB > HFVB:
        FVB = HFVB
    if FVB > ZVBEZJ:
        FVB = ZVBEZJ
    FVBSO = math.ceil(FVB + VBEZBSO * TAB1(J) / 100)
    if FVBSO > TAB2(J):
        FVBSO = TAB2(J)
    HFVBZSO = (VBEZB + VBEZBSO) / 100 - FVBSO
    FVBZSO = math.ceil(FVBZ + VBEZBSO / 100) 
    if FVBZSO > HFVBZSO:
        FVBZSO = math.ceil(HFVBZSO)
    if FVBZSO > TAB3(J):
        FVBZSO = TAB3(J)
    HFVBZ = VBEZB/100 - FVB
    if FVBZ > HFVBZ:
        FVBZ = math.ceil(HFVBZ)
    MRE4ALTE()

def MRE4ALTE():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    if ALTER1 == 0:
        ALTE = 0
    else:
        if AJAHR < 2006:
            K = 1
        elif AJAHR < 2040:
            K = AJAHR - 2004
        else:
            K = 36
        BMG = ZRE4J - ZVBEZJ
        ALTE = math.ceil(BMG * TAB4(K))
        HBALTE = TAB5(K)
        if ALTE > HBALTE:
            ALTE = HBALTE

def TAB1(J):
    if J < 17:
        return (0.4 - 0.016 *(J-1))
    else:
        return (0.16 - 0.008 *(J-16))
        
def TAB2(J):
    if J < 17:
        return (3000 - 120 * (J - 1))
    else:
        return (1200 - 60 * (J - 16))

def TAB3(J):
    if J < 17:
        return (900 - 36 * (J - 1))
    else:
        return (360 - 18 * (J - 16))
    
def TAB4(K):
    if K < 17:
        return (0.4 - 0.016 * (K - 1))
    else:
        return (0.16 - 0.008 * (K - 16))

def TAB5(K):
    if J < 17:
        return (1900 - 76 * (K - 1))
    else:
        return (760 - 38 * (K - 16))

def MRE4ABZ():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    ZRE4 = ZRE4J - FVB - ALTE - JLFREIB + JLHINZU
    if ZRE4 < 0:
        ZRE4 < 0
    ZRE4VP = ZRE4J
    if KENNVMT == 2:
        ZRE4VP = ZRE4VP - ENTSCH /10
    ZVBEZ = ZVBEZJ - FVB
    if ZVBEZ < 0:
        ZVBEZ = 0

def MBERECH():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    MZTABFB()
    VFRB = (ANP + FVB + FVBZ) * 100
    MLSTJAHR
    WVFRB = (ZVE - GFB) * 100
    if WVFRB < 0:
        WVFRB = 0
    LSTJAHR = ST * F
    UPLSTLZZ()
    UPVKVLZZ()
    if ZKF > 0:
        ZTABFB = ZTABFB + KFB
        MRE4ABZ()
        MLSTJAHR()
        JBMG = ST * F
    else:
        JBMG = LSTJAHR
    MSOLZ()

def MZTABFB():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    ANP = 0
    if ZVBEZ >= 0:
        if ZVBEZ < FVBZ:
            FVBZ = ZVBEZ
    if STKL < 6: 
        if ZVBEZ > 0:
            if ZVBEZ - FVBZ < 102:
                ANP = math.ceil(ZVBEZ - FVBZ)
            else:
                ANP = 102
    else:
        FVBZ = 0
        FVBZSO = 0
    if STKL < 6:
         if ZRE4 > ZVBEZ:
            if ZRE4 - ZVBEZ < 1200:
                math.ceil(ANP = ANP + ZRE4 - ZVBEZ)
            else:
                ANP = ANP + 1200
    KZTAB = 1
    if STKL == 1:
        SAP = 36
        KFB = ZKF * 8952
    elif STKL == 2:
        EFA = 4008
        SAP = 36 
        KFB = ZKF * 8952
    elif STKL == 3:
        STKL = 3
        SAP = 36 
        KFB = ZKF * 8952
    elif STKL == 4:
        SAP = 36
        KFB = ZKF * 4476
    elif STKL == 5:
        SAP = 36
        KFB = 0
    else:
        KFB = 0
    ZTABFB = EFA + ANP + SAP + FVBZ

def MLSTJAHR():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    UPEVP
    if KENNVMT != 1:
        ZVE = ZRE4 - ZTABFB - VSP
        UPMLST()
    else:
        ZVE = ZRE4 - ZTABFB - VSP - VMT / 100 - VKAPA / 100
        if ZVE < 0:
            ZVE = (ZVE + VMT / 100 + VKAPA / 100) / 5
            UPMLST()
            ST = ST * 5
        else:
            UPMLST()
            STOVMT = ST
            ZVE = ZVE + (VMT + VKAPA) / 500
            UPMLST()
            ST = (ST - STOVMT) * 5 + STOVMT

def UPVKVLZZ():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    UPVKV()
    JW = VKV
    UPANTEIL()
    VKVLZZ = ANTEIL1

def UPVKV():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    if PKV > 0:
        if VSP2 > VSP3:
            VKV = VSP2 * 100
        else:
            VKV = VSP3 * 100
    else:
        VKV = 0

def UPLSTLZZ():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    JW = LSTJAHR * 100
    UPANTEIL()
    LSTLZZ = ANTEIL1

def UPMLST():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    if ZVE < 1:
        ZVE = 0
        X = 0
    else:
        X = math.floor(ZVE / KZTAB)
    if STKL < 5:
        UPTAB23()
    else:
        MST5_6()

def UPEVP():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    if KRV > 1:
        VSP1 = 0
    else:
        if ZRE4VP > BBGRV:
            ZRE4VP = BBGRV
        VSP1 = TBSVORV * ZRE4VP
        VSP1 = VSP1 * RVSATZAN
    VSP2 = 0.12 * ZRE4VP
    if STKL == 3:
        VHB = 3000
    else:
        VHB = 1900
    if VSP2 > VHB:
        VSP2 = VHB
    math.ceil(VSPN = VSP1 + VSP2)
    MVSP()
    if VSPN > VSP:
        VSP = VSPN

def MVSP():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    if ZRE4VP > BBGKVPV:
        ZRE4VP = BBGKVPV
    if PKV > 0:
        if STKL == 6:
            VSP3 = 0
        else:
            VSP3 = PKPV * 12 / 100
            if PKV == 2:
                VSP3 = VSP3 - ZRE4VP * (KVSATZAG + PVSATZAG)
    else:
        VSP3 = ZRE4VP * (KVSATZAN + PVSATZAN)
    VSP = math.ceil(VSP3 + VSP1)

def MST5_6():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    ZZX = X
    if ZZX > W2STKL5:
        ZX = W2STKL5
        UP5_6()
        if ZZX > W3STKL5:
            ST = math.floor(ST + (W3STKL5 - W2STKL5) * 0.42)
            ST = math.floor(ST + (ZZX - W3STKL5) * 0.45)
        else:
            ST = math.floor(ST + (ZZX - W2STKL5) * 0.42)
    else:
        ZX = ZZX
        UP5_6()
        if ZZX > W1STKL5:
            VERGL = ST
            ZX = W1STKL5
            UP5_6()
            HOCH = math.floor(ST + (ZZX - W1STKL5) * 0.42)
            if HOCH < VERGL:
                ST = HOCH
            else:
                ST = VERGL

def UP5_6():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    X = ZX * 1.25
    UPTAB23()
    ST1 = ST
    X = ZX * 0.75
    UPTAB23()
    ST2 = ST
    DIFF = (ST1 - ST2) * 2
    MIST = math.floor(ZX * 0.14)
    if MIST > DIFF:
        ST = MIST
    else:
        ST = DIFF

def MSOLZ():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    SOLZFREI = SOLZFREI * KZTAB
    if JBMG > SOLZFREI:
        SOLZJ = math.floor(JBMG * 5.5 / 100)
        SOLZMIN = (JBMG - SOLZFREI) * 11.9 / 100
        if SOLZMIN < SOLZJ:
            SOLZJ = SOLZMIN
        JW = SOLZJ * 100
        UPANTEIL()
        SOLZLZZ = ANTEIL1
    else:
        SOLZLZZ = 0
    if R > 0:
        JW = JBMG * 100
        UPANTEIL()
        BK = ANTEIL1
    else:
        BK = 0

def UPANTEIL():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    if LZZ == 1:
        ANTEIL1 = JW
    elif LZZ == 2:
        ANTEIL1 = math.floor(JW / 12)
    elif LZZ == 3:
        ANTEIL1 = math.floor(JW * 7 / 360)
    else:
        ANTEIL1 = math.floor(JW / 360)

def MSONST():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZFREI, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFRE, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX  
    LZZ = 1
    if ZMVB == 0 :
        ZMVB = 12
    if SONSTB == 0 or MBV == 0:
        VKVSONST = 0
        LSTSO = 0
        STS = 0
        SOLZS = 0
        BKS = 0
    else:
        MOSONST()
        UPVKV()
        VKVSONST = VKV
        ZRE4J = (JRE4 + SONSTB) / 100
        ZVBEZJ = (JVBEZ + VBS) / 100
        VBEZBSO = STERBE
        MRE4SONST()
        MLSTJAHR()
        WVFRBM = (ZVE - GFB) * 100
        if WVFRBM < 0:
            WVFRBM = 0
        UPVKV()
        VKVSONST = VKV - VKVSONST
        LSTSO = ST * 100
        STS = math.floor((LSTSO - LSTOSO) * F)
        STSMIN()

def STSMIN():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZFREI, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFRE, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX  
    if STS < 0:
        if MBV != 0:
            LSTLZZ = LSTLZZ + STS
            if LSTLZZ < 0:
                LSTLZZ = 0
            SOLZLZZ = math.floor(SOLZLZZ + STS * 5.5 / 100)
            if SOLZLZZ < 0:
                SOLZLZZ = 0
            BK = BK + STS
            if BK < 0:
                BK = 0
        STS = 0
        SOLZS = 0
    else:
        MSOLZSTS()
    if R > 0:
        BKS = STS
    else:
        BKS = 0

def MSOLZSTS():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZFREI, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFRE, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX  
    if ZKF > 0 :
        SOLZSZVE = ZVE - KFB
    else:
        SOLZSZVE = ZVE
    if SOLZSZVE < 1:
        SOLZSZVE = 0
        X = 0
    else:
        X = math.floor(SOLZSZVE / KZTAB)
    if STKL < 5:
        UPTAB23()
    else:
        MST5_6()
    SOLZSBMG = math.floor(ST * F)
    if SOLZSBMG > SOLZFREI:
        SOLZS = math.floor(STS * 5.5 / 100)
    else:
        SOLZS = 0 

def MVMT():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZFREI, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFRE, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX  
    if VKAPA < 0:
        VKAPA = 0
    if VMT + VKAPA > 0:
        if LSTSO == 0:
            MOSONST()
            LST1 = LSTOSO
        else:
            LST1 = LSTSO
        VBEZBSO = STERBE + VKAPA
        ZRE4J = (JRE4 + SONSTB + VMT + VKAPA) / 100
        ZVBEZJ = (JVBEZ + VBS + VKAPA) / 100
        KENNVMT = 2
        MRE4SONST()
        MLSTJAHR()
        LST3 = ST * 100
        MRE4ABZ()
        ZRE4VP = ZRE4VP - JRE4ENT / 100 - SONSTENT / 100
        KENNVMT = 1
        MLSTJAHR()
        LST2 = ST * 100
        STV = LST2 - LST1
        LST3 = LST3 - LST1
        if LST3 < STV:
            STV = LST3
        if STV < 0:
            STV = 0
        else:
            STV = STV * F
        SOLZVBMG = STV / 100 + JBMG
        if SOLZVBMG > SOLZFREI:
            SOLZV = math.floor(STV * 5.5 / 100)
        else:
            SOLZV = 0
        if R > 0:
            BKV = STV
        else:
            BKV = 0 
    else:
        STV = 0
        SOLZV = 0
        BKV = 0

def MOSONST():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZFREI, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFRE, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VFRBS1, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX  
    ZRE4J = JRE4 / 100
    ZVBEZJ = JVBEZ / 100
    JLFREIB = JFREIB / 100
    JLHINZU = JHINZU / 100
    MRE4()
    MRE4ABZ()
    ZRE4VP = ZRE4VP - JRE4ENT / 100
    MZTABFB()
    VFRBS1 = (ANP + FVB + FVBZ) * 100
    MLSTJAHR()
    WVFRBO = (ZVE - GFB) * 100
    if WVFRBO < 0:
        WVFRBO = 0
    LSTOSO = ST * 100

def MRE4SONST():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZFREI, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFRE, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX  
    MRE4()
    FVB = FVBSO
    MRE4ABZ()
    ZRE4VP = ZRE4VP + MBV / 100 - JRE4ENT / 100 - SONSTENT / 100
    FVBZ = FVBZSO
    MZTABFB()
    VFRBS2 = (ANP + FVB + FVBZ) * 100 - VFRBS1

def UPTAB23():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    if X < GFB + 1:
        ST = 0
    elif X < 16000:
        Y = (X - GFB) / 10000
        RW = Y * 979.18
        RW = RW + 1400
        ST = math.floor(RW * Y)
    elif X < 62810:
        Y = (X - 15999) / 10000
        RW = Y * 192.59
        RW = RW + 2397
        RW = RW * Y
        ST = math.floor(RW + 966.53)
    elif X < 277826:
        ST = math.floor(X * 0.42 - 9972.98)
    else:
        ST = math.floor(X * 0.45 - 18307.73)
    ST = ST * KZTAB  

def ausgeben():
    global AF, AJAHR, ALTER1, ENTSCH, F, JFREIB, JHINZU, JRE4, JRE4ENT, JVBEZ, KRV, KVZ, LZZ, LZZFREIB, LZZHINZU, MBV, PKPV, PKV, PVS, PVZ, R, RE4, SONSTB, SONSTENT, STERBE, STKL, VBEZ, VBEZM, VBEZS, VBS, VJAHR, VKAPA, VMT, ZKF, ZMVB, BK, BKS, BKV, LSTLZZ, SOLZIZZ, SOLZS, SOLZV, STS, STV, VKVLZZ, VKVSONST, ALTE, ANP, ANTEIL1, BBGKVPV, BBGRV, BMG, DIFF, EFA, FVB, FVBSO, FVBZ, FVBZSO, GFB, HBALTE, HFVB, HFVBZ, HFVBZSO, HOCH, J, JBMG, JLFREIB, JLHINZU, JW, K, KENNVMT, KFB, KVSATZAG, KVSATZAN, KZTAB, LSTJAHR, LST1, LST2, LST3, LSTOSO, LSTSO, MIST, PVSATZAG, PVSATZAN, RVSATZAN, RW, SAP, SOLZFREI, SOLZJ, SOLZMIN, SOLZSBMG, SOLZSZVE, SOLZVBMG, ST, ST1, ST2, STOVMT, TAB1, TAB2, TAB3, TAB4, TAB5, TBSVORV, VBEZB, VBEZBSO, VERGL, VHB, VKV, VSP, VSPN, VSP1, VSP2, VSP3, W1STKL5, W2STKL5, W3STKL5, X, Y, ZRE4, ZRE4J, ZRE4VP, ZTABFB, ZVBEZ, ZVBEZJ, ZVE, ZX, ZZX
    print("Lohnsteuer : ", LSTLZZ / 100, "€")
    print("Solidaritätsbeitrag : ", SOLZLZZ / 100, "€")
    print("Grundlage Kirchensteuer: ", BK / 100, "€")

eingeben()
MPARA()
MRE4JL()
VBEZBSO = 0
KENNVMT = 0
MRE4()
MRE4ABZ()
MBERECH()
MSONST()
MVMT()
print ("\n")
ausgeben()